name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Run basic test
      run: |
        echo "Testing model load"
        python -c "import joblib; joblib.load('app/iris_model.pkl')"

    - name: Build Docker image
      run: docker build -t iris-app ./app
      
    - name: Run Docker container
      run: docker run -d -p 5000:5000 iris-app
